Repository trailofbits/twa, pull requests merged in 2018-10, with the labels that each got.

#35 Add an option for CSV output
  twa
Labels: enhancement, hacktoberfest

#36 Audit robots.txt
  twa
Labels: enhancement, hacktoberfest

#34 twa: Formal codes for negative results
  README.md
  twa
Labels: enhancement

#44 Improve some previously unknown CAA record cases.
  twa
Labels: bug
